name: update

on:
  push:
    branches:
      - master
  pull-request:
    branches: 
      - '*'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      -run: curl -v -X POST https://import-dot-confetti-349319.uw.r.appspot.com/update/devfestnantes