runtime: python27
api_version: 1
threadsafe: true
default_expiration: "100d"
handlers:
  - url: /
    static_files: index.html
    upload: index.html
    secure: always
    http_headers:
      cache-control: public, max-age=60, must-revalidate

    # All files with extensions are considered static
  - url: /(.+\..+)
    static_files: \1
    upload: (.*)
    secure: always
    http_headers:
      cache-control: public, max-age=60, must-revalidate

    # The rest are folders
  - url: /(.*)/
    static_files: \1/index.html
    upload: (.+)/index.html
    secure: always
    http_headers:
      cache-control: public, max-age=60, must-revalidate
  - url: /(.*)
    static_files: \1/index.html
    upload: (.+)/index.html
    secure: always
    http_headers:
      cache-control: public, max-age=60, must-revalidate

    # 404
  - url: /en/(.*)
    static_files: en/404.html
    upload: en/404.html
    http_headers:
      cache-control: public, max-age=60, must-revalidate
  - url: /(.*)
    static_files: 404.html
    upload: 404.html
    http_headers:
      cache-control: public, max-age=60, must-revalidate

error_handlers:
  - file: 404.html
